# Generated by Django 3.0.3 on 2020-03-27 08:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/catalog/categories/', verbose_name='Изображение категории')),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание для главной')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание категории')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать ?')),
                ('is_in_index_catalog', models.BooleanField(db_index=True, default=False, verbose_name='Показывать в каталоге на главной ?')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара')),
                ('name_lower', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена')),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул')),
                ('discount', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Скидка %')),
                ('units', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Ед.Измерения')),
                ('material', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Материал')),
                ('size', models.CharField(blank=True, max_length=15, null=True, verbose_name='Размер')),
                ('weight', models.CharField(blank=True, max_length=15, null=True, verbose_name='Вес')),
                ('complect', models.CharField(blank=True, max_length=15, null=True, verbose_name='Комплект')),
                ('thickness', models.CharField(blank=True, max_length=15, null=True, verbose_name='Толщина')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Description страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать товар ?')),
                ('is_present', models.BooleanField(db_index=True, default=True, verbose_name='Товар в наличии ?')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Товар новинка ?')),
                ('buys', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название производителя')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/catalog/manufacturers/', verbose_name='Лого')),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на странице')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод (для создания рандомного значения оставить пустым)')),
                ('promo_discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка на заказ')),
                ('use_counts', models.IntegerField(blank=True, default=1, verbose_name='Кол-во использований')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Неограниченное кол-во использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия безлимитного кода')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тега')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('seoText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст для СЕО')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Относится к категории')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подкатегории')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание подкатегории')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка на все товары в подкатегории %')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='item.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/catalog/items/', verbose_name='Изображение товара')),
                ('image_small', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение для товара',
                'verbose_name_plural': 'Изображения для товара',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='manufactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Manufactor', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.SubCategory', verbose_name='Подкатегории'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, db_index=True, to='item.Tag', verbose_name='Теги'),
        ),
    ]
