# Generated by Django 3.0.3 on 2020-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображается,'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображается,'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображается,'),
        ),
    ]
