# Generated by Django 3.0.3 on 2020-03-11 12:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufactor',
            old_name='page_C',
            new_name='page_keywords',
        ),
        migrations.RemoveField(
            model_name='manufactor',
            name='short_description',
        ),
        migrations.AddField(
            model_name='category',
            name='manufactor',
            field=models.ManyToManyField(db_index=True, to='item.Manufactor', verbose_name='Производители'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='manufactor',
            field=models.ManyToManyField(db_index=True, to='item.Manufactor', verbose_name='Производители'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на странице'),
        ),
    ]
