# Generated by Django 3.0.3 on 2020-03-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactor',
            name='subcategory',
        ),
    ]
