# Generated by Django 3.0.3 on 2020-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200328_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order_num',
            field=models.IntegerField(default=100),
        ),
    ]
