# Generated by Django 3.0.3 on 2020-03-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200311_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_img/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Manufactor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/%d/%s', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='image',
            field=models.ImageField(blank=True, upload_to='manufactor_img/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название производителя'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка на заказ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тега'),
        ),
    ]
