# Generated by Django 3.0.3 on 2020-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_manufactor_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactor',
            name='subcategory',
            field=models.ManyToManyField(db_index=True, to='item.SubCategory', verbose_name='Отностится к подкатегориям'),
        ),
    ]
