# Generated by Django 3.0.3 on 2020-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200311_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='manufactor',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='manufactor',
        ),
        migrations.AddField(
            model_name='manufactor',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='categories', to='item.Category', verbose_name='Отностится к категориям'),
        ),
        migrations.AddField(
            model_name='manufactor',
            name='subcategory',
            field=models.ManyToManyField(db_index=True, related_name='subcategories', to='item.SubCategory', verbose_name='Отностится к подкатегориям'),
        ),
    ]
