# Generated by Django 3.0.3 on 2020-03-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_manufactor_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufactor',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
