# Generated by Django 3.0.3 on 2020-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200322_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(blank=True, default='не указано', max_length=5, null=True, verbose_name='Ед.Измерения'),
        ),
    ]
