# Generated by Django 3.1 on 2020-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20201130_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='manufactor',
            field=models.ManyToManyField(blank=True, related_name='subcat_manufactors', to='item.Manufactor', verbose_name='Производители'),
        ),
        migrations.AlterField(
            model_name='category',
            name='manufactor',
            field=models.ManyToManyField(blank=True, related_name='cat_manufactors', to='item.Manufactor', verbose_name='Производители'),
        ),
    ]
