# Generated by Django 3.0.3 on 2020-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200311_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactor',
            name='category',
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='subcategory',
            field=models.ManyToManyField(db_index=True, to='item.SubCategory', verbose_name='Отностится к подкатегориям'),
        ),
    ]
