# Generated by Django 3.0.3 on 2020-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200323_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Ед.Измерения'),
        ),
    ]
