# Generated by Django 3.1.4 on 2021-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='at_home_page2',
            field=models.BooleanField(default=True, verbose_name='На главной (баннер2)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
