# Generated by Django 3.0.3 on 2020-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200326_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/catalog/manufacturers/', verbose_name='Лого'),
        ),
    ]
