# Generated by Django 3.1.4 on 2021-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210202_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='at_home_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='at_home_page2',
            field=models.BooleanField(default=False, verbose_name='На главной (баннер2)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='at_sale_page',
            field=models.BooleanField(default=False, verbose_name='На акциях'),
        ),
    ]
