# Generated by Django 3.1.4 on 2021-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_banner_at_home_page3'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='num',
            field=models.IntegerField(default=10),
        ),
    ]
