# Generated by Django 3.1.4 on 2021-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_banner_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('num',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='category',
            name='num',
            field=models.IntegerField(default=10),
        ),
    ]
