# Generated by Django 3.1.4 on 2021-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20210208_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description страницы'),
        ),
    ]
