# Generated by Django 3.1.4 on 2021-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210208_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='page_keywords',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание '),
        ),
    ]
